/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSFrameView.h"

@class NSDocumentDragButton;

@interface NSTitledFrame : NSFrameView
{
    int resizeFlags;
    NSDocumentDragButton *fileButton;
    struct _NSSize titleCellSize;
}

+ (void)initialize;
+ (float)_windowBorderThickness:(NSUInteger)fp8;
+ (float)_minXWindowBorderWidth:(NSUInteger)fp8;
+ (float)_maxXWindowBorderWidth:(NSUInteger)fp8;
+ (float)_minYWindowBorderHeight:(NSUInteger)fp8;
+ (BOOL)_resizeFromEdge;
+ (struct _NSRect)frameRectForContentRect:(struct _NSRect)fp8 styleMask:(NSUInteger)fp24;
+ (struct _NSRect)contentRectForFrameRect:(struct _NSRect)fp8 styleMask:(NSUInteger)fp24;
+ (struct _NSSize)minFrameSizeForMinContentSize:(struct _NSSize)fp8 styleMask:(NSUInteger)fp16;
+ (struct _NSSize)minContentSizeForMinFrameSize:(struct _NSSize)fp8 styleMask:(NSUInteger)fp16;
+ (float)minFrameWidthWithTitle:(id)fp8 styleMask:(NSUInteger)fp12;
+ (struct _NSSize)_titleCellSizeForTitle:(id)fp8 styleMask:(NSUInteger)fp12;
+ (float)_titleCellHeight:(NSUInteger)fp8;
+ (float)_windowTitlebarTitleMinHeight:(NSUInteger)fp8;
+ (float)_titlebarHeight:(NSUInteger)fp8;
+ (struct _NSSize)sizeOfTitlebarButtons:(NSUInteger)fp8;
+ (float)windowTitlebarLinesSpacingWidth:(NSUInteger)fp8;
+ (float)windowTitlebarTitleLinesSpacingWidth:(NSUInteger)fp8;
+ (float)_contentToFrameMinXWidth:(NSUInteger)fp8;
+ (float)_contentToFrameMaxXWidth:(NSUInteger)fp8;
+ (float)_contentToFrameMinYHeight:(NSUInteger)fp8;
+ (float)_contentToFrameMaxYHeight:(NSUInteger)fp8;
- (id)initWithFrame:(struct _NSRect)fp8 styleMask:(NSUInteger)fp24 owner:(id)fp28;
- (void)dealloc;
- (void)setIsClosable:(BOOL)fp8;
- (void)setIsResizable:(BOOL)fp8;
- (void)_resetTitleFont;
- (void)_setUtilityWindow:(BOOL)fp8;
- (BOOL)isOpaque;
- (BOOL)worksWhenModal;
- (void)propagateFrameDirtyRects:(struct _NSRect)fp8;
- (void)_showDrawRect:(struct _NSRect)fp8;
- (id)frameHighlightColor;
- (id)frameShadowColor;
- (void)setFrameOrigin:(struct _NSPoint)fp8;
- (void)tileAndSetWindowShape:(BOOL)fp8;
- (void)tile;
- (void)_tileTitlebarAndRedisplay:(BOOL)fp8;
- (void)setTitle:(id)fp8;
- (BOOL)_shouldRepresentFilename;
- (void)setRepresentedFilename:(id)fp8;
- (void)_drawTitleStringIn:(struct _NSRect)fp8 withColor:(id)fp24;
- (id)titleFont;
- (id)titleButtonOfClass:(Class)fp8;
- (id)initTitleButton:(id)fp8;
- (id)newCloseButton;
- (id)newZoomButton;
- (id)newMiniaturizeButton;
- (id)newFileButton;
- (id)fileButton;
- (void)_removeButtons;
- (void)_updateButtons;
- (BOOL)_eventInTitlebar:(id)fp8;
- (BOOL)acceptsFirstMouse:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)rightMouseDown:(id)fp8;
- (void)rightMouseUp:(id)fp8;
- (NSInteger)resizeEdgeForEvent:(id)fp8;
- (struct _NSSize)_resizeDeltaFromPoint:(struct _NSPoint)fp8 toEvent:(id)fp16;
- (struct _NSRect)_validFrameForResizeFrame:(struct _NSRect)fp8 fromResizeEdge:(NSInteger)fp24;
- (struct _NSRect)frame:(struct _NSRect)fp8 resizedFromEdge:(NSInteger)fp24 withDelta:(struct _NSSize)fp28;
- (BOOL)constrainResizeEdge:(int *)fp8 withDelta:(struct _NSSize)fp12 elapsedTime:(float)fp20;
- (void)resizeWithEvent:(id)fp8;
- (NSInteger)resizeFlags;
- (void)resetCursorRects;
- (void)setDocumentEdited:(BOOL)fp8;
- (struct _NSSize)miniaturizedSize;
- (struct _NSSize)minFrameSize;
- (float)_windowBorderThickness;
- (float)_windowTitlebarXResizeBorderThickness;
- (float)_windowTitlebarYResizeBorderThickness;
- (float)_windowResizeBorderThickness;
- (float)_minXWindowBorderWidth;
- (float)_maxXWindowBorderWidth;
- (float)_minYWindowBorderHeight;
- (id)_customTitleCell;
- (void)_invalidateTitleCellSize;
- (void)_invalidateTitleCellWidth;
- (float)_titleCellHeight;
- (struct _NSSize)_titleCellSize;
- (float)_titlebarHeight;
- (struct _NSRect)titlebarRect;
- (struct _NSRect)_maxTitlebarTitleRect;
- (struct _NSRect)_titlebarTitleRect;
- (float)_windowTitlebarTitleMinHeight;
- (struct _NSRect)dragRectForFrameRect:(struct _NSRect)fp8;
- (struct _NSSize)sizeOfTitlebarButtons;
- (struct _NSSize)_sizeOfTitlebarFileButton;
- (float)_windowTitlebarButtonSpacingWidth;
- (float)_minXTitlebarButtonsWidth;
- (float)_maxXTitlebarButtonsWidth;
- (NSInteger)_numberOfTitlebarLines;
- (float)windowTitlebarLinesSpacingWidth;
- (float)windowTitlebarTitleLinesSpacingWidth;
- (float)_minLinesWidthWithSpace;
- (struct _NSRect)_minXTitlebarLinesRectWithTitleCellRect:(struct _NSRect)fp8;
- (struct _NSRect)_maxXTitlebarLinesRectWithTitleCellRect:(struct _NSRect)fp8;
- (float)_minXTitlebarDecorationMinWidth;
- (float)_maxXTitlebarDecorationMinWidth;
- (struct _NSPoint)_closeButtonOrigin;
- (struct _NSPoint)_zoomButtonOrigin;
- (struct _NSPoint)_collapseButtonOrigin;
- (struct _NSPoint)_fileButtonOrigin;
- (float)_maxYTitlebarDragHeight;
- (float)_minXTitlebarDragWidth;
- (float)_maxXTitlebarDragWidth;
- (float)_contentToFrameMinXWidth;
- (float)_contentToFrameMaxXWidth;
- (float)_contentToFrameMinYHeight;
- (float)_contentToFrameMaxYHeight;
- (struct _NSRect)contentRect;
- (float)_windowResizeCornerThickness;
- (struct _NSRect)_minYResizeRect;
- (struct _NSRect)_minYminXResizeRect;
- (struct _NSRect)_minYmaxXResizeRect;
- (struct _NSRect)_minXResizeRect;
- (struct _NSRect)_minXminYResizeRect;
- (struct _NSRect)_minXmaxYResizeRect;
- (struct _NSRect)_maxYResizeRect;
- (struct _NSRect)_maxYminXResizeRect;
- (struct _NSRect)_maxYmaxXResizeRect;
- (struct _NSRect)_maxXResizeRect;
- (struct _NSRect)_maxXminYResizeRect;
- (struct _NSRect)_maxXmaxYResizeRect;
- (struct _NSRect)_minXTitlebarResizeRect;
- (struct _NSRect)_maxXTitlebarResizeRect;
- (struct _NSRect)_minXBorderRect;
- (struct _NSRect)_maxXBorderRect;
- (struct _NSRect)_maxYBorderRect;
- (struct _NSRect)_minYBorderRect;

@end

